### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by maov19** [maov19/space-travelers-hub#25]
## Dear reviewer

According to the project requirements, here are the items for review:

✔️ Link to our project: [Space Traveler's Hub](https://github.com/maov19/space-travelers-hub/projects/1)
✔️ Amount of team members: 2
- @maov19 
- @Koshao-sys

**Comment by IngDavidTM** [comment]
## Hi Team 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The issue shows the number of members ✅ 

## Suggested changes

- [ ] It is necessary to include a link to your project, but specifically, it should be a link to the [Kanban board](https://github.com/maov19/space-travelers-hub/projects/1) rather than the repository. Please make this correction. Providing the Kanban link helps others to better understand the project's progress and tasks, and enables easier collaboration and communication among team members :+1:.

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by maov19** [comment]
Hi @IngDavidTM , thanks for your feedback!
The issue observed is already fixed 🔧 
Please let us know if there is something else we should work on.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @IngDavidTM and @Koshao-sys,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by maov19** [comment]
Approved by reviewer
